package com.wzx.babiq.server.attachment;

/**
 * Stable, path-free attachment failure reasons exposed to protocol adapters.
 */
public enum AttachmentErrorCode {
    ATTACHMENT_EMPTY,
    ATTACHMENT_LIMIT_EXCEEDED,
    ATTACHMENT_FILE_TOO_LARGE,
    ATTACHMENT_TOTAL_TOO_LARGE,
    ATTACHMENT_PATH_INVALID,
    ATTACHMENT_NOT_FOUND,
    ATTACHMENT_NOT_REGULAR_FILE,
    ATTACHMENT_TYPE_UNSUPPORTED,
    ATTACHMENT_CHANGED,
    ATTACHMENT_PARSE_FAILED,
    ATTACHMENT_ENCRYPTED,
    ATTACHMENT_TEXT_LIMIT_EXCEEDED,
    ATTACHMENT_IMAGE_TOO_LARGE,
    ATTACHMENT_MODEL_UNSUPPORTED,
    ATTACHMENT_CLIPBOARD_FAILED,
    ATTACHMENT_PARSE_TIMEOUT,
    ATTACHMENT_PARSE_OVERLOADED,
    ATTACHMENT_ARCHIVE_UNSAFE,
    ATTACHMENT_REFERENCE_AMBIGUOUS
}
